sudo: false
language: node_js
node_js:
  - node
  - 8
  - 7
  - 6
cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test

after_success:
  - yarn codecov

fail_fast: true
