notifications:
  email: false
sudo: false
language: node_js
node_js:
  - node
  - 8
  - 7
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g cross-env codecov istanbul rimraf webpack
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - yarn codecov

fail_fast: true
